
package ws.soap.client.async;

import java.util.concurrent.Future;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.Response;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloService", targetNamespace = "http://soap.ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloService {


    /**
     * 
     * @param arg0
     * @return
     *     returns javax.xml.ws.Response<ws.soap.client.async.SayHelloResponse>
     */
    @WebMethod(operationName = "sayHello")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://soap.ws/", className = "ws.soap.client.async.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://soap.ws/", className = "ws.soap.client.async.SayHelloResponse")
    public Response<SayHelloResponse> sayHelloAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "sayHello")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://soap.ws/", className = "ws.soap.client.async.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://soap.ws/", className = "ws.soap.client.async.SayHelloResponse")
    public Future<?> sayHelloAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<SayHelloResponse> asyncHandler);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://soap.ws/", className = "ws.soap.client.async.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://soap.ws/", className = "ws.soap.client.async.SayHelloResponse")
    public String sayHello(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns javax.xml.ws.Response<ws.soap.client.async.SayHelloWorldResponse>
     */
    @WebMethod(operationName = "sayHelloWorld")
    @RequestWrapper(localName = "sayHelloWorld", targetNamespace = "http://soap.ws/", className = "ws.soap.client.async.SayHelloWorld")
    @ResponseWrapper(localName = "sayHelloWorldResponse", targetNamespace = "http://soap.ws/", className = "ws.soap.client.async.SayHelloWorldResponse")
    public Response<SayHelloWorldResponse> sayHelloWorldAsync();

    /**
     * 
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "sayHelloWorld")
    @RequestWrapper(localName = "sayHelloWorld", targetNamespace = "http://soap.ws/", className = "ws.soap.client.async.SayHelloWorld")
    @ResponseWrapper(localName = "sayHelloWorldResponse", targetNamespace = "http://soap.ws/", className = "ws.soap.client.async.SayHelloWorldResponse")
    public Future<?> sayHelloWorldAsync(
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<SayHelloWorldResponse> asyncHandler);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHelloWorld", targetNamespace = "http://soap.ws/", className = "ws.soap.client.async.SayHelloWorld")
    @ResponseWrapper(localName = "sayHelloWorldResponse", targetNamespace = "http://soap.ws/", className = "ws.soap.client.async.SayHelloWorldResponse")
    public String sayHelloWorld();

}
